### ISSUE TITLE
Cart's issue

### ISSUE THREAD

**Issue by anhhhhe160062** [pqhung3007/swp391-project-online-shop#38]
Nếu thay đổi số lượng bằng cách type vào thì nó k update
![image](https://user-images.githubusercontent.com/100254135/176810076-6987bd55-7165-4f65-9c12-e19c96165508.png)
Thay đổi số lượng bằng cách type vào field:
![image](https://user-images.githubusercontent.com/100254135/176810115-ac2e7095-6182-4090-b395-b257023a0b04.png)

**Comment by pqhung3007** [comment]
Giá trị của input chỉ để hiển thị số lượng sản phẩm. Người dùng sẽ thay đổi số lượng dựa trên 2 nút tăng giảm
 `<a class="btn btn-link px-2"
                                                           href="updatequantity?action=dec&id=${c.value.product.productId}">
                                                            <i class="fas fa-minus"></i>
                                                        </a>
                                                        <input id="form1" name="quantity" value="${c.value.quantity}" type="number"
                                                               style="max-width: 3rem; text-align: center"
                                                               class="form-control-sm"
                                                               />
                                                        <a class="btn btn-link px-2"
                                                           href="updatequantity?action=inc&id=${c.value.product.productId}">
                                                            <i class="fas fa-plus"></i>
                                                        </a>`
