### ISSUE TITLE
Customer orders' page issue

### ISSUE THREAD

**Issue by pqhung3007** [pqhung3007/swp391-project-online-shop#54]
<img width="943" alt="image" src="https://user-images.githubusercontent.com/49837290/179439215-e60edf1d-3784-4eaa-837e-b8475c472d10.png">
Nhìn vào giao diện trên sẽ có các vấn đề như sau:

- Time ordered chưa được hiển thị
- Khi mới đặt hàng xong và chưa có sự tương tác với seller + shipper, ô status đang không hiển thị gì. Should be "waiting/processing"
- Khi customer chưa có đơn hàng nào thì cần hiển thị "You have not ordered anything" hoặc đại loại vậy
- Bên order detail còn hiển thị sai thông tin. Phần ở dưới gạch ngang cần hiển thị total price thay vì number of product
- Mục All Order/Processing/History bị thừa. Cần xóa

**Comment by qnhanhh** [comment]
còn timeordered chưa được hiển thị
