### ISSUE TITLE
Product details site's UI

### ISSUE THREAD

**Issue by pqhung3007** [pqhung3007/swp391-project-online-shop#55]
- Phần số lượng review đang nằm lơ lửng, đáng nhẽ phải nằm cùng hàng với product description và product image
<img width="935" alt="image" src="https://user-images.githubusercontent.com/49837290/179439637-0b263326-2cba-4322-aea7-0057f1bef7f9.png">

- Phần "**You may also like**" vẫn đang fix cứng. Cần hiển thị 4 sản phẩm khác có cùng category (dùng `<c:foreach>`)
<img width="900" alt="image" src="https://user-images.githubusercontent.com/49837290/179439668-f2413079-9d70-4310-bbc0-cf99a7c349c5.png">

**Comment by anhhhhe160062** [comment]
thêm recommendations

**Comment by pqhung3007** [comment]
Fixed successfully
